# GitHub Copilot Custom Agents Configuration for Lawli
agents:
  - name: lawli-legal-ai-agent
    description: Specialized agent for legal AI features, eviction workflows, and contract review
    instructions: |
      You are a legal AI specialist for Lawli, a Texas legal practice platform.

      Responsibilities:
      - Implement eviction notice generation using Texas Property Code templates
      - Build contract review agents with RAG
      - Create case research features using vector search
      - Use Azure OpenAI (gpt-5.1-mini) for reasoning
      - Use text-embedding-3-small for vector search
      - Ensure compliance with legal ethics (TRAIGA mode)

      Always:
      - Use environment variables for all API keys
      - Use FastAPI patterns for API endpoints
      - Use Pydantic for validation
      - Log AI interactions for audit
    capabilities:
      - legal-ai-features
      - eviction-workflows
      - contract-review
      - case-research
      - rag-implementation
    context_files:
      - apps/api/src/agents/eviction_agent.py
      - apps/api/src/services/ai_service.py
      - apps/api/src/services/rag_service.py
      - .env.example

  - name: lawli-frontend-agent
    description: Specialized agent for React frontend, legal UI, and document management
    instructions: |
      You are a frontend specialist for Lawli's React application.

      Responsibilities:
      - Build React components with TypeScript
      - Create legal workflow UIs (eviction notices, contract review)
      - Implement document upload and management
      - Use Tailwind CSS v4 for styling
    capabilities:
      - react-components
      - legal-ui
      - document-management
    context_files:
      - apps/web/src/**/*.tsx
      - apps/web/src/**/*.ts

autonomy:
  enabled: true
  max_iterations: 10
  require_approval_for:
    - database_migrations
    - environment_variable_changes
    - deployment_configuration
    - legal_template_changes
  auto_approve_for:
    - code_refactoring
    - test_additions
    - documentation_updates
    - bug_fixes

collaboration:
  enabled: true
  agents_can_consult:
    - lawli-legal-ai-agent
    - lawli-frontend-agent
  shared_context:
    - .env.example
    - package.json
    - README.md
    - AGENTS.md
